// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE-OSU file in the repository root for full licence text.

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using NUnit.Framework;
using osu.Game.Screens.Banchosucks.Clicker;
using osu.Game.Tests.Resources;

namespace osu.Game.Tests.NonVisual
{
    /// <summary>
    /// Banchosucks: the client's <see cref="ClickerEconomy"/> and the server plugin's <c>economy.py</c> must produce the
    /// same numbers. Both read <c>clicker-balance-fixture.json</c> (generated by the plugin's <c>make_fixture.py</c>).
    /// </summary>
    [TestFixture]
    public class BanchosucksClickerEconomyTest
    {
        private const double tolerance = 1e-6;

        [Test]
        public void TestBalanceEmbedded()
        {
            var balance = ClickerBalance.Instance;
            Assert.That(balance.Season, Is.EqualTo(3));
            Assert.That(balance.BpmEpoch, Is.EqualTo(3));
            Assert.That(balance.MaxBpm, Is.EqualTo(500));
            Assert.That(balance.Producers.Length, Is.EqualTo(11));
            Assert.That(balance.PrestigeProducers.Length, Is.EqualTo(3));
            Assert.That(balance.PrestigeSoftcap, Is.EqualTo(50));
            Assert.That(balance.Tree.Length, Is.GreaterThan(30));
            Assert.That(balance.Producer("cursor")!.Icon, Is.Not.EqualTo(default(osu.Framework.Graphics.Sprites.IconUsage)));
            Assert.That(balance.Node("wysi")!.Requires, Is.EquivalentTo(new[] { "aim_5", "speed_5" }));
        }

        [Test]
        public void TestFixture()
        {
            using var stream = TestResources.OpenResource("Banchosucks/clicker-balance-fixture.json");
            var fixture = JsonSerializer.Deserialize<Fixture>(stream)!;
            Assert.That(fixture.Cases, Is.Not.Empty);

            foreach (var testCase in fixture.Cases)
            {
                var state = testCase.State.Deserialize<ClickerState>()!;
                var modifier = testCase.Modifier?.Deserialize<ClickerModifier>();
                var economy = new ClickerEconomy(ClickerBalance.Instance, state, modifier);
                var expected = testCase.Expected;
                long now = fixture.Now;

                var cursor = ClickerBalance.Instance.Producer("cursor")!;
                var taiko = ClickerBalance.Instance.Producer("taiko")!;

                assertClose(expected, "base_per_second", economy.BasePerSecond, testCase.Name);
                assertClose(expected, "per_second", economy.PerSecond(now), testCase.Name);
                assertClose(expected, "click_value", economy.ClickValue(now), testCase.Name);
                assertClose(expected, "production_multiplier", economy.ProductionMultiplier, testCase.Name);
                assertClose(expected, "spent_total", economy.SpentTotal(), testCase.Name);
                assertClose(expected, "buildings", economy.Buildings, testCase.Name);
                assertClose(expected, "total_stars", economy.TotalStars, testCase.Name);
                assertClose(expected, "prestige_total", economy.PrestigeTotal, testCase.Name);
                assertClose(expected, "prestige_pending", economy.PrestigePending, testCase.Name);
                assertClose(expected, "prestige_available", economy.PrestigeAvailable, testCase.Name);
                assertClose(expected, "respec_cost", economy.RespecCost, testCase.Name);
                assertClose(expected, "cursor_cost", economy.ProducerCost(cursor), testCase.Name);
                assertClose(expected, "taiko_star_cost", economy.StarCost(taiko, economy.NextStarIndex("taiko")), testCase.Name);
                assertClose(expected, "cursor_display_rate", economy.DisplayRate("cursor"), testCase.Name);
                assertClose(expected, "offline_10000s", economy.OfflineEarnings(10_000), testCase.Name);
                assertClose(expected, "offline_rate", economy.OfflineRate, testCase.Name);
                assertClose(expected, "offline_cap_seconds", economy.OfflineCapSeconds, testCase.Name);
                assertClose(expected, "encore_reward", economy.EncoreReward(now), testCase.Name);
                assertClose(expected, "daily_reward", economy.DailyReward(now), testCase.Name);
                assertClose(expected, "spinner_reward", economy.SpinnerReward(now, false), testCase.Name);
                assertClose(expected, "kiai_spinner_reward", economy.SpinnerReward(now, true), testCase.Name);
                assertClose(expected, "slider_reward_80", economy.SliderReward(now, 0.8), testCase.Name);
                assertClose(expected, "expedition_slots", economy.ExpeditionSlots, testCase.Name);

                Assert.That(economy.StanceUnlocked, Is.EqualTo(expected["stance_unlocked"].GetBoolean()), $"{testCase.Name}: stance_unlocked");

                string[] newMedals = expected["new_medals"].EnumerateArray().Select(e => e.GetString()!).ToArray();
                Assert.That(economy.NewMedals().Select(m => m.Id).OrderBy(id => id), Is.EqualTo(newMedals.OrderBy(id => id)), $"{testCase.Name}: new_medals");
            }
        }

        private static void assertClose(Dictionary<string, JsonElement> expected, string key, double actual, string name)
        {
            double value = expected[key].GetDouble();
            // relative tolerance: the numbers span many orders of magnitude
            Assert.That(actual, Is.EqualTo(value).Within(tolerance * System.Math.Max(1, System.Math.Abs(value))), $"{name}: {key}");
        }

        private class Fixture
        {
            [JsonPropertyName("now")] public long Now { get; set; }
            [JsonPropertyName("cases")] public List<FixtureCase> Cases { get; set; } = new List<FixtureCase>();
        }

        private class FixtureCase
        {
            [JsonPropertyName("name")] public string Name { get; set; } = string.Empty;
            [JsonPropertyName("state")] public JsonElement State { get; set; }
            [JsonPropertyName("modifier")] public JsonElement? Modifier { get; set; }
            [JsonPropertyName("expected")] public Dictionary<string, JsonElement> Expected { get; set; } = new Dictionary<string, JsonElement>();
        }
    }
}
